addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.9")
addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.5.0")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker" % "1.5.0")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.10")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.9.0")